#!/usr/bin/env bash
# Open/sync nwg-look settings across GTK, gsettings, cursor env and Mango.

set -euo pipefail

usage() {
    printf 'Usage: %s [--open|--sync]\n' "$0" >&2
}

mode="${1:---sync}"
case "$mode" in
    --open|--sync) ;;
    -h|--help)
        usage
        exit 0
        ;;
    *)
        usage
        exit 2
        ;;
esac

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
gtk3_settings="$config_dir/gtk-3.0/settings.ini"
gtk4_settings="$config_dir/gtk-4.0/settings.ini"
gtk2_settings="$config_dir/gtkrc-2.0"
mango_env="$config_dir/mango/custom/nwg-look-env.conf"
mango_cursor="$config_dir/mango/custom/nwg-look-mango.conf"

command -v nwg-look >/dev/null 2>&1 || {
    printf 'nwg-look not found\n' >&2
    exit 1
}

if [ "$mode" = "--open" ]; then
    nwg-look
fi

# Ensure nwg-look exports GTK files from the currently stored settings.
nwg-look -x >/dev/null 2>&1 || true

[ -f "$gtk3_settings" ] || {
    printf 'GTK 3 settings not found: %s\n' "$gtk3_settings" >&2
    exit 1
}

get_setting() {
    local key="$1"
    awk -F= -v key="$key" '
        $1 == key {
            value = $2
            sub(/^[[:space:]]+/, "", value)
            sub(/[[:space:]]+$/, "", value)
            print value
            exit
        }
    ' "$gtk3_settings"
}

gtk_theme="$(get_setting gtk-theme-name)"
icon_theme="$(get_setting gtk-icon-theme-name)"
font_name="$(get_setting gtk-font-name)"
cursor_theme="$(get_setting gtk-cursor-theme-name)"
cursor_size="$(get_setting gtk-cursor-theme-size)"
prefer_dark="$(get_setting gtk-application-prefer-dark-theme)"

gtk_theme="${gtk_theme:-Adwaita}"
icon_theme="${icon_theme:-Adwaita}"
font_name="${font_name:-Sans 11}"
cursor_theme="${cursor_theme:-default}"
cursor_size="${cursor_size:-24}"
prefer_dark="${prefer_dark:-0}"

if ! [[ "$cursor_size" =~ ^[0-9]+$ ]]; then
    cursor_size=24
fi

font_size="${font_name##* }"
font_family="${font_name% $font_size}"
if ! [[ "$font_size" =~ ^[0-9]+([.][0-9]+)?$ ]] || [ -z "$font_family" ]; then
    font_family="$font_name"
    font_size=11
fi
qt_general_font="$font_family,$font_size,-1,5,50,0,0,0,0,0"
qt_fixed_font="Monospace,$font_size,-1,5,50,0,0,0,0,0"

mkdir -p \
    "$config_dir/gtk-4.0" \
    "$config_dir/mango/custom" \
    "$HOME/.icons/default"

cat > "$gtk4_settings" <<EOF
[Settings]
gtk-theme-name=$gtk_theme
gtk-icon-theme-name=$icon_theme
gtk-font-name=$font_name
gtk-cursor-theme-name=$cursor_theme
gtk-cursor-theme-size=$cursor_size
gtk-application-prefer-dark-theme=$prefer_dark
EOF

cat > "$gtk2_settings" <<EOF
# Generated by nwg-look-sync.sh from GTK 3 settings.
gtk-theme-name="$gtk_theme"
gtk-icon-theme-name="$icon_theme"
gtk-font-name="$font_name"
gtk-cursor-theme-name="$cursor_theme"
gtk-cursor-theme-size=$cursor_size
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle="hintslight"
gtk-xft-rgba="rgb"
EOF

cat > "$HOME/.icons/default/index.theme" <<EOF
[Icon Theme]
Inherits=$cursor_theme
EOF

sync_qtct() {
    local path="$1"
    [ -f "$path" ] || return 0

    if grep -q '^icon_theme=' "$path"; then
        sed -i "s|^icon_theme=.*|icon_theme=$icon_theme|" "$path"
    elif grep -q '^\[Appearance\]' "$path"; then
        sed -i "/^\[Appearance\]/a icon_theme=$icon_theme" "$path"
    fi

    if grep -q '^\[Fonts\]' "$path"; then
        if grep -q '^general=' "$path"; then
            sed -i "s|^general=.*|general=\"$qt_general_font\"|" "$path"
        else
            sed -i "/^\[Fonts\]/a general=\"$qt_general_font\"" "$path"
        fi

        if grep -q '^fixed=' "$path"; then
            sed -i "s|^fixed=.*|fixed=\"$qt_fixed_font\"|" "$path"
        else
            sed -i "/^\[Fonts\]/a fixed=\"$qt_fixed_font\"" "$path"
        fi
    else
        printf '\n[Fonts]\ngeneral="%s"\nfixed="%s"\n' "$qt_general_font" "$qt_fixed_font" >> "$path"
    fi
}

sync_qtct "$config_dir/qt5ct/qt5ct.conf"
sync_qtct "$config_dir/qt6ct/qt6ct.conf"

cat > "$mango_env" <<EOF
# Generated by nwg-look-sync.sh. Change values in nwg-look, not here.
env=XCURSOR_THEME,$cursor_theme
env=XCURSOR_SIZE,$cursor_size
EOF

cat > "$mango_cursor" <<EOF
# Generated by nwg-look-sync.sh. Change values in nwg-look, not here.
cursor_theme = $cursor_theme
cursor_size = $cursor_size
EOF

if command -v gsettings >/dev/null 2>&1; then
    gsettings set org.gnome.desktop.interface gtk-theme "$gtk_theme" || true
    gsettings set org.gnome.desktop.interface icon-theme "$icon_theme" || true
    gsettings set org.gnome.desktop.interface font-name "$font_name" || true
    gsettings set org.gnome.desktop.interface cursor-theme "$cursor_theme" || true
    gsettings set org.gnome.desktop.interface cursor-size "$cursor_size" || true
    if [ "$prefer_dark" = "1" ]; then
        gsettings set org.gnome.desktop.interface color-scheme prefer-dark || true
    else
        gsettings set org.gnome.desktop.interface color-scheme default || true
    fi
fi

export XCURSOR_THEME="$cursor_theme"
export XCURSOR_SIZE="$cursor_size"
dbus-update-activation-environment --systemd XCURSOR_THEME XCURSOR_SIZE >/dev/null 2>&1 || true
systemctl --user import-environment XCURSOR_THEME XCURSOR_SIZE >/dev/null 2>&1 || true
mmsg -d reload_config >/dev/null 2>&1 || true

if command -v notify-send >/dev/null 2>&1; then
    notify-send "nwg-look" "Tema GTK, fonte e cursor sincronizados" >/dev/null 2>&1 || true
fi

printf 'Synced GTK theme=%s icon=%s font=%s cursor=%s size=%s\n' \
    "$gtk_theme" "$icon_theme" "$font_name" "$cursor_theme" "$cursor_size"
