# https://mangowm.github.io/docs/configuration/monitors/
# Left edge of each column = sum of widths of monitors to its left (no gaps here).

# monitorrule=name:…,refresh:…,x:0,y:0,scale:1,vrr:0,rr:0
monitorrule=name:^DP-2$,width:1920,height:1080,refresh:60,x:0,y:0,scale:1,vrr:0,rr:0
monitorrule=name:^DP-1$,width:2560,height:1440,refresh:165.08,x:1920,y:0,scale:1,vrr:0,rr:0
