[Appearance]
color_scheme_path=/home/geko/.local/share/color-schemes/Darkly.colors
custom_palette=true
icon_theme=WhiteSur-dark
style=Darkly

[Fonts]
general="Roboto Flex,11,-1,5,50,0,0,0,0,0"
fixed="Monospace,11,-1,5,50,0,0,0,0,0"
