# Mango colors.conf (appearance)

rootcolor=0x201b14ff
bordercolor=0x444444ff
focuscolor=0xc9b890ff
maximizescreencolor=0xc9b890ff
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff
borderpx=4
no_border_when_single=0
gappih=2
gappiv=2
gappoh=2
gappov=2
smartgaps=0
focused_opacity=1.0
unfocused_opacity=1.0
overviewgappi=5
overviewgappo=30
ov_tab_mode=0
hotarea_size=10
enable_hotarea=1
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
cursor_size=24