# Indecisius Wofi — Clipboard with compact thumbnails
width=690
height=460
location=center
lines=8
columns=1
prompt=Clipboard
allow_images=true
image_size=64
allow_markup=true
parse_search=true
dmenu-parse_action=true
insensitive=true
matching=fuzzy
hide_scroll=false
cache_file=/dev/null
style=/home/geko/.config/wofi/spotlight.css
