width=690
height=460
location=top_left
x=423
y=202
lines=8
columns=1
prompt=Mango layout
allow_images=true
allow_markup=true
parse_search=true
dmenu-parse_action=true
insensitive=true
matching=fuzzy
hide_scroll=false
image_size=28
cache_file=/dev/null
style=/home/geko/.config/wofi/spotlight.css
