width=690
height=460
location=center
lines=8
columns=1
prompt=Search
allow_images=true
allow_markup=true
parse_search=true
insensitive=true
matching=fuzzy
drun-ignore_metadata=true
hide_scroll=true
image_size=28
no_actions=true
style=/home/geko/.config/wofi/spotlight.css
