# Custom key bindings
# Add your personal keybindings here

# Power menu (wlogout)
bind=SUPER,BackSpace,spawn_shell,pkill wlogout || wlogout

# Toggle floating window
bind=SUPER+ALT,Space,togglefloating

# Mango layout picker / layout families
# Available from `mmsg -L`: T S G M K CT RT VS VT VG VK DW
bind=SUPER+ALT,period,centerwin
bind=SUPER+ALT,comma,centerwin
bind=SUPER+ALT,1,spawn,~/.config/mango/scripts/cycle-layout-family.sh T RT VT CT
bind=SUPER+ALT,2,spawn,~/.config/mango/scripts/cycle-layout-family.sh S VS
bind=SUPER+ALT,3,spawn,~/.config/mango/scripts/cycle-layout-family.sh G VG
bind=SUPER+ALT,4,spawn,mmsg -s -l M
bind=SUPER+ALT,5,spawn,~/.config/mango/scripts/cycle-layout-family.sh K VK

bind=SUPER+ALT,6,spawn,mmsg -s -l DW     # Dwindle
