#!/bin/bash
# Generate live accent colors from the current wallpaper with matugen.
# Replaces cybr red at runtime while keeping safe fallbacks.

set -euo pipefail

fallback_primary="#F24848"
fallback_primary_container="#331215"
fallback_on_primary_container="#30F291"
fallback_surface="#05070D"
fallback_on_surface="#F24848"
fallback_secondary="#80d4aa"
fallback_secondary_container="#264d3c"
fallback_tertiary="#90caf9"
fallback_tertiary_container="#274b61"

image="${1:-}"

if [ -z "$image" ] && command -v awww >/dev/null 2>&1; then
    image=$(awww query 2>/dev/null | sed -n 's/.*currently displaying: image: //p' | head -n 1 || true)
fi

if [ -z "$image" ] || [ ! -f "$image" ]; then
    exit 0
fi

command -v matugen >/dev/null 2>&1 || exit 0
command -v jq >/dev/null 2>&1 || exit 0

tmp_config=$(mktemp)
trap 'rm -f "$tmp_config"' EXIT
printf '[config]\n[templates]\n' > "$tmp_config"

json=$(matugen image "$image" --config "$tmp_config" --prefer saturation --json hex --dry-run --quiet 2>/dev/null || true)
[ -n "$json" ] || exit 0

primary=$(printf '%s' "$json" | jq -r '.colors.primary.default.color // empty')
primary_container=$(printf '%s' "$json" | jq -r '.colors.primary_container.default.color // empty')
on_primary_container=$(printf '%s' "$json" | jq -r '.colors.on_primary_container.default.color // empty')
secondary=$(printf '%s' "$json" | jq -r '.colors.secondary.default.color // empty')
secondary_container=$(printf '%s' "$json" | jq -r '.colors.secondary_container.default.color // empty')
tertiary=$(printf '%s' "$json" | jq -r '.colors.tertiary.default.color // empty')
tertiary_container=$(printf '%s' "$json" | jq -r '.colors.tertiary_container.default.color // empty')
surface=$(printf '%s' "$json" | jq -r '.colors.surface.default.color // empty')
on_surface=$(printf '%s' "$json" | jq -r '.colors.on_surface.default.color // empty')
error=$(printf '%s' "$json" | jq -r '.colors.error.default.color // empty')

primary=${primary:-$fallback_primary}
primary_container=${primary_container:-$fallback_primary_container}
on_primary_container=${on_primary_container:-$fallback_on_primary_container}
secondary=${secondary:-$fallback_secondary}
secondary_container=${secondary_container:-$fallback_secondary_container}
tertiary=${tertiary:-$fallback_tertiary}
tertiary_container=${tertiary_container:-$fallback_tertiary_container}
surface=${surface:-$fallback_surface}
on_surface=${on_surface:-$fallback_on_surface}
error=${error:-#ffb4ab}

mkdir -p "$HOME/.config/waybar/MangoWC/svg" "$HOME/.config/wofi" "$HOME/.config/fish/conf.d" "$HOME/.config/cava" "$HOME/.config/mango/hyprmango"

cat > "$HOME/.config/mango/hyprmango/colors.matugen.conf" <<EOF
# Generated by update-matugen-accent.sh from: $image
rootcolor=0x$(printf '%s' "$surface" | tr -d '#')ff
bordercolor=0x$(printf '%s' "$primary_container" | tr -d '#')ff
focuscolor=0x$(printf '%s' "$primary" | tr -d '#')ff
maximizescreencolor=0x$(printf '%s' "$primary" | tr -d '#')ff
urgentcolor=0x$(printf '%s' "$error" | tr -d '#')ff
globalcolor=0x$(printf '%s' "$primary_container" | tr -d '#')ff
EOF

cat > "$HOME/.config/waybar/MangoWC/matugen.css" <<EOF
/* Generated by update-matugen-accent.sh from: $image */
@define-color matugen-primary $primary;
@define-color matugen-primary-container $primary_container;
@define-color matugen-on-primary-container $on_primary_container;
@define-color matugen-surface $surface;
@define-color matugen-on-surface $on_surface;
@define-color matugen-error $error;
EOF

write_waybar_arrow() {
    local name="$1"
    local direction="$2"
    local color="$3"
    local path_data

    if [ "$direction" = "left" ]; then
        path_data="M0 7.62939e-05H14V19.0002L0 31.0002V7.62939e-05Z"
    else
        path_data="M14 7.507e-05L-2.71012e-06 7.62939e-05L-1.22392e-06 17.0002L14 31.0002L14 7.507e-05Z"
    fi

    cat > "$HOME/.config/waybar/MangoWC/svg/$name-$direction.svg" <<EOF
<svg width="14" height="31" viewBox="0 0 14 31" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="$path_data" fill="$color"/>
</svg>
EOF
}

for direction in left right; do
    write_waybar_arrow no1 "$direction" "$surface"
    write_waybar_arrow re0 "$direction" "$primary"
    write_waybar_arrow re1 "$direction" "$primary_container"
    write_waybar_arrow gr0 "$direction" "$on_primary_container"
done

cat > "$HOME/.config/wofi/matugen.css" <<EOF
/* Generated by update-matugen-accent.sh from: $image */
@define-color matugen_primary $primary;
@define-color matugen_primary_container $primary_container;
@define-color matugen_on_primary_container $on_primary_container;
@define-color matugen_surface $surface;
@define-color matugen_on_surface $on_surface;
@define-color matugen_error $error;
EOF

cat > "$HOME/.config/cava/config" <<EOF
# Indecisius Cava config
# Generated by update-matugen-accent.sh from: $image

[general]
framerate = 60
autosens = 1
bars = 0
bar_width = 2
bar_spacing = 1
center_align = 1

[input]
method = pipewire
source = auto

[output]
method = noncurses
orientation = bottom
channels = stereo
show_idle_bar_heads = 1

[color]
background = '$surface'
foreground = '$primary'
gradient = 1
gradient_color_1 = '$primary_container'
gradient_color_2 = '$secondary_container'
gradient_color_3 = '$tertiary_container'
gradient_color_4 = '$secondary'
gradient_color_5 = '$primary'
gradient_color_6 = '$tertiary'
gradient_color_7 = '$on_primary_container'

[smoothing]
monstercat = 1
waves = 0
noise_reduction = 77
EOF

if [ -f "$HOME/.config/wofi/style.css" ]; then
    python - "$HOME/.config/wofi/style.css" "$primary" "$primary_container" "$on_primary_container" "$surface" "$on_surface" "$error" <<'PY'
import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
values = {
    "matugen_primary": sys.argv[2],
    "matugen_primary_container": sys.argv[3],
    "matugen_on_primary_container": sys.argv[4],
    "matugen_surface": sys.argv[5],
    "matugen_on_surface": sys.argv[6],
    "matugen_error": sys.argv[7],
}
text = path.read_text()
for name, value in values.items():
    text = re.sub(rf"@define-color\s+{re.escape(name)}\s+#[0-9A-Fa-f]{{6}};", f"@define-color {name} {value};", text)
path.write_text(text)
PY
fi

cat > "$HOME/.config/fish/conf.d/indecisius-matugen.fish" <<EOF
# Generated by update-matugen-accent.sh from: $image
set -g fish_color_normal (string replace '#' '' '$primary')
set -g fish_color_command (string replace '#' '' '$primary')
set -g fish_color_cwd (string replace '#' '' '$on_primary_container')
set -g fish_color_error (string replace '#' '' '$error') --bold --background=(string replace '#' '' '$primary_container')
set -g fish_color_param (string replace '#' '' '$on_surface')
set -g fish_color_operator (string replace '#' '' '$on_primary_container')
set -g fish_color_quote (string replace '#' '' '$on_primary_container')
set -g fish_color_selection (string replace '#' '' '$on_primary_container') --bold --background=(string replace '#' '' '$primary_container')
set -g fish_color_search_match (string replace '#' '' '$on_primary_container') --bold --background=(string replace '#' '' '$primary_container')
EOF

if [ -f "$HOME/.config/starship.toml" ]; then
    sed -i -E \
        -e "s/^re0 = \"#[0-9A-Fa-f]{6}\"/re0 = \"$primary\"/" \
        -e "s/^re2 = \"#[0-9A-Fa-f]{6}\"/re2 = \"$primary_container\"/" \
        -e "s/^gr0 = \"#[0-9A-Fa-f]{6}\"/gr0 = \"$on_primary_container\"/" \
        "$HOME/.config/starship.toml"
fi

pkill -SIGUSR2 waybar 2>/dev/null || true
pkill -USR2 cava 2>/dev/null || true

# Reload wofi (it reads CSS on launch) and notify
pkill wofi 2>/dev/null || true
notify-send "Matugen" "Cores atualizadas do wallpaper:\n$image" -i preferences-desktop-theme 2>/dev/null || true
